import { USER_ROUTES, AUTH_ROUTES } from "./pathRoutes";
import { ROLES } from "./roles";
import { AUTH_FORM, LABEL_FORM } from "./authForm";
import { SYSTEM_NAME, ME } from "./app.constant";
import {
  REGEX_PASSWORD,
  REGEX_FIRST_NAME,
  REGEX_LAST_NAME,
} from "./regex.constant";

import {
  INPUT_FIRST_NAME_REQUIRED,
  INPUT_LAST_NAME_REQUIRED,
  INPUT_EMAIL_REQUIRED,
  INPUT_PASSWORD_REQUIRED,
  INPUT_FIRST_FORMAT,
  INPUT_LAST_FORMAT,
  INPUT_EMAIL_FORMAT,
  INPUT_PASSWORD_FORMAT,
} from "./labelsFormMessages";

import { ERROR_DEFAULT } from "./responsesApi";
import { API_ROUTES_USER } from "./apiRoutes.constant";
import { MENU_ITEM_CUSTOMER, MENU_ITEM_ADMIN } from "./menuItems";

export {
  USER_ROUTES,
  MENU_ITEM_CUSTOMER,
  MENU_ITEM_ADMIN,
  API_ROUTES_USER,
  ERROR_DEFAULT,
  AUTH_ROUTES,
  ROLES,
  AUTH_FORM,
  SYSTEM_NAME,
  LABEL_FORM,
  ME,
  REGEX_PASSWORD,
  REGEX_FIRST_NAME,
  REGEX_LAST_NAME,
  INPUT_FIRST_NAME_REQUIRED,
  INPUT_LAST_NAME_REQUIRED,
  INPUT_EMAIL_REQUIRED,
  INPUT_PASSWORD_REQUIRED,
  INPUT_FIRST_FORMAT,
  INPUT_LAST_FORMAT,
  INPUT_EMAIL_FORMAT,
  INPUT_PASSWORD_FORMAT,
};
